language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:kalakris/cmake; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install cmake; fi # Update cmake
  - if [ $CC == clang ] && [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install emacs build-essential texlive texinfo imagemagick; fi

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target ciao && cmake .. && cmake --build . --target msat && cmake .. && cmake --build . && cmake --build . --target ftclp

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then echo "missing deploy"; fi

branches:
  only:
    - dev

notifications:
  email: false

env:
  - LANG="en_US.UTF-8" 

os:
  - linux

