language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $CC == clang ] && [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install emacs build-essential texlive texinfo imagemagick gcc-multilib libc6-i386 libc6-dev-i386 g++-multilib; fi
  - # CIAOTGZ=CiaoDE-latest.tar.gz; wget http://ciao-lang.org/packages/master/$CIAOTGZ; mkdir $CIAODIR; tar --directory "$CIAODIR" --strip-components=1 -xvzf "$TRAVIS_BUILD_DIR/$CIAOTGZ"

before_script:
  - # cd $CIAODIR; ./ciaosetup configure --instype=local --cc=$CC

script:
  - # cd $CIAODIR; ./ciaosetup build
  - # cd $CIAODIR; ./ciaosetup install
  - # cd $TRAVIS_BUILD_DIR
  - # . $CIAODIR/ciao/etc/DOTprofile
  - # ciaoc hw.pl
  - # ./hw
  - make install # TODO: This should be 'make install-deps'
  - make all

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then echo "missing deploy"; fi

branches:
  only:
    - master

notifications:
  email: false

env:
  - LANG="en_US.UTF-8" FTCLP_INSTALL=$TRAVIS_BUILD_DIR/ftclp

os:
  - linux

