#!/bin/bash

#*******************************************************************************
# Installation script for gmp
#
# Author: Jorge. A Navas, The University of Melbourne 2014
#*****************************************************************************/


# Exit on any failed command
set -o errexit

# Exit with message error
die() {
    echo "$@" 1>&2
    exit 1
}

# get directory name
get_dir() {
	pushd "$1" > /dev/null
	pwd
	popd > /dev/null
}


# download urls
w_get() {
    wget "$1" 
}

# Directory of this script
SCRIPT_DIR="`get_dir \`dirname ${BASH_SOURCE[0]}\``"

### gmp tarball's  url
TARBALL=gmp-6.0.0a.tar.bz2
GMP_TARBALL_URL="https://ftp.gnu.org/gnu/gmp/${TARBALL}"

### directory where to install ciao
GMP_INSTALL="$SCRIPT_DIR/third-party/gmp-6.0.0"

if [[ ! -d "$GMP_INSTALL" ]]; then
    ## Download files
    w_get "$GMP_TARBALL_URL"
    ## extract files
    tar xvjf "$TARBALL" 
    rm -f "$TARBALL" 
    mv "$SCRIPT_DIR/gmp-6.0.0" "$SCRIPT_DIR/third-party"
    ## install GMP for 32 bits
    cd "$GMP_INSTALL"
    ABI=32 ./configure --prefix="$GMP_INSTALL/build" --enable-cxx
    make -C "$GMP_INSTALL"
    make install -C "$GMP_INSTALL"
    ln -s "$GMP_INSTALL/build/lib/libgmp.a"  "$SCRIPT_DIR/lib/libgmp.a"
    ln -s "$GMP_INSTALL/build/lib/libgmpxx.a"  "$SCRIPT_DIR/lib/libgmpxx.a"
    echo -e "Installation finished successfully\n"
    echo -e "gmp for 32-bits has been installed in $GMP_INSTALL." 
fi

